dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "dylanaubrey-github"
    token:
      secure: $SONAR_TOKEN
script:
  - npm test
  - sonar-scanner